version: "3.9"

services:
  tracker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
